Initial Backend Setup
Fundo-Patronos/centro-de-carreiras pull request #42
Opened 2024-08-26 15:39 UTC by gabsrp2002

# Overview

This PR contains the initial setup for the backend of the project.

## File organization
- **alembic**: Contains database migration history
  - More info [here](https://alembic.sqlalchemy.org/en/latest/)
- **app**: Main directory
  - Uses [fastapi](https://fastapi.tiangolo.com)
- **tests**: Test directory
  - Uses [pytest](https://docs.pytest.org/en/stable/) with [pytest-cov](https://pytest-cov.readthedocs.io/en/latest/) for line coverage report and [httpx](https://www.python-httpx.org) to test api routes.

Closes #3

2024-08-26 16:02 UTC, Brunoatf requested changes
Colocar o merge para staging ao invés de main. Eu também sempre esqueço de fazer isso kkkk

2024-08-26 16:25 UTC, gabsrp2002 commented
> Colocar o merge para staging ao invés de main. Eu também sempre esqueço de fazer isso kkkk

Feito!

2024-08-27 21:24 UTC, jpcmorais16 commented on backend/tests/crud/test_student.py
Esse teste realmente acessaria o banco de dados? Se for o caso, não sei se isso é muito legal, mesmo que seja o banco de testes. Acho que mockar seria uma opção melhor para testes automatizados, talvez com um mock db em contêiner.

2024-08-27 22:04 UTC, gabsrp2002 commented on backend/tests/crud/test_student.py
Ele cria um banco de dados in-memory (sqlite) novo pra cada teste e apaga no final. Isso garante que os testes são isolados e permite que a gente controle o que está no banco durante cada teste. A dependência injetada está definida no _conftest.py_. Não acho que tenha problema fazer assim. Ainda mais porque podemos fazer um teste de integração direto só trocando o nome da variável de ambiente `TEST_DATABASE_URL`

2024-08-27 23:55 UTC, jpcmorais16 commented on backend/tests/crud/test_student.py
Aula

2024-08-27 23:55 UTC, jpcmorais16 approved these changes

2024-08-28 15:28 UTC, Brunoatf approved these changes

2024-08-28 22:01 UTC, merged