Docs/api endpoint design
Fundo-Patronos/centro-de-carreiras pull request #44
Opened 2024-09-03 04:06 UTC by MatheusHenriqueSS

## Primeiro Rascunho da Definição da API do Centro de Carreiras

### Documentação da API

- **`api-documentation`:** Contém as definições básicas das entidades e relações que serão armazenadas no Airtable, bem como o funcionamento das rotas para conversão ao formato adequado da API do Airtable.

- **`swagger.json`:** Define a especificação das rotas no formato OpenAPI. Você pode visualizar o diagrama interativo importando o `swagger.json` aqui: [Swagger Editor](https://editor.swagger.io/).
Ilustração do json de especificação no swagger UI: 
<img width="749" alt="Screenshot 2024-09-03 at 01 05 12" src="https://github.com/user-attachments/assets/4bb0504f-1644-4dd2-9a75-75bf1c888a2e">

### Foco das Rotas

O foco das rotas está no seguinte fluxo:
- **Disponibilidade dos Mentores:** Gerenciamento dos horários disponíveis dos mentores.
- **Agendamento de Reuniões:** Processo para marcar reuniões com mentores com base na disponibilidade.

### Pontos de Atenção

- **Rota de Notificações (`/notifications`):** Atualmente está um pouco genérica. Precisamos definir o fluxo de notificações antes e depois de um agendamento, para confirmar que ele foi bem-sucedido.

- **Rota de Aprovação Manual (`/auth/manual-approval-request`):** É um webhook que receberá uma solicitação quando uma aprovação for registrada no Airtable. Esse webhook gerenciará o fluxo de notificar o aluno, criar a entidade base no banco de dados e gerar o link para o cadastro.

### Referências: 
- https://airtable.com/developers/web/api/introduction
- https://airtable.com/developers/web/api/webhooks-overview

Closes: #39

2024-09-03 18:35 UTC, gabsrp2002 approved these changes
LGTM🚀

Nitpick: Lembrando que o fastAPI gera uma documentação automática das rotas que desenvolvermos. Seria legal migrar a documentação do swagger pra lá depois que tivermos as rotas implementadas. O que acha? Só pra garantir que a documentação está sempre em dia com a implementação no backend.

2024-09-03 23:04 UTC, Brunoatf commented
Boa. Acho que essa doc já dá uma visão inicial legal do que precisa ser implementado para o backend. Conforme formos percebendo o que precisa ser feito podemos ir fazendo alterações. Ao final do projeto, concordo com o Paiva que é melhor só termos a doc automática, mas por enquanto acaba sendo legal para fins de planejamento.

2024-09-03 23:04 UTC, Brunoatf approved these changes

2024-09-03 23:07 UTC, Brunoatf requested changes

2024-09-03 23:07 UTC, Brunoatf commented on docs/api/api-documentation.md
> +# Documentação da API
Acho massa por enquanto trocar a pasta docs para algo como "planning", para que os demais saibam que isso ainda não é algo absoluto e final. Ao final do projeto, usaremos a doc automática msm

2024-09-08 23:42 UTC, Brunoatf approved these changes

2024-09-08 23:43 UTC, merged