Auth Process
Fundo-Patronos/centro-de-carreiras pull request #57
Opened 2024-09-23 23:08 UTC by gabsrp2002

This PR implements auth endpoints in the backend API.

This PR includes:
- Sign up and sign in endpoints
- Verify endpoint to send a verification email
- Some tests implementations
- Uses dependency injection to choose what database to use during test or production.

Closes #8

2024-09-27 21:06 UTC, TheDeas343 requested changes

2024-10-02 19:03 UTC, gabsrp2002 commented on backend/app/crud/opportunities_table.py
> +        opportunity = self.db.read_one(table_id=self.table_id, params=params)
O read_one nunca retorna None. Caso o dado não seja encontrado, ele joga um erro de `DataNotFound`

2024-10-02 19:04 UTC, gabsrp2002 commented on backend/app/crud/users_table.py
> +    def get_user_by_email(self, email: str) -> User:
Não existe uma anotação de exceção em python... Procurei e não achei, mas concordo que seria bom. Alguma sugestão pra deixar isso mais claro?

2024-10-02 19:06 UTC, gabsrp2002 commented on backend/app/dependencies.py
> +def get_db() -> Generator[Database, None, None]:
Ele é um singleton (a classe abstrata Database garante isso). Ainda assim, só uma requisição é feita, uma vez que não precisamos criar um conexão pro banco de dados. Só um request pra uma API

2024-10-02 19:08 UTC, gabsrp2002 commented on backend/app/routes/auth.py
> +        raise HTTPException(
Não, no caso do signup é esperado que o usuário não esteja no banco de dados. No signin ele tem que estar

2024-10-04 03:11 UTC, TheDeas343 approved these changes

2024-10-04 03:11 UTC, TheDeas343 approved these changes

2024-10-04 11:47 UTC, jpcmorais16 approved these changes
LGTM!

2024-10-04 11:48 UTC, merged