Feature/frontend ci
Fundo-Patronos/centro-de-carreiras pull request #82
Opened 2024-10-22 18:59 UTC by gmikio

## Feature/frontend-ci: Fix Build & Lint Issues

This pull request aims to merge the `feature/frontend-ci` branch into `staging`. The main focus of this update was to address several build and linting issues, ensuring that the project can now successfully run through all CI/CD checks.

### Key Changes
- **Fixed ESLint Errors and Warnings**: Resolved all linting issues to ensure the codebase meets quality standards.
- **Resolved TypeScript Build Issues**: Addressed TypeScript errors that were preventing successful builds.
- **Updated Docker Configuration**: Modified the Dockerfile and related configurations to enable successful Docker builds for deployment.

These improvements are crucial for preparing the frontend for a smooth Docker build process and subsequent deployment to production environments. Please review and approve to integrate these important fixes.

2024-10-22 21:51 UTC, Brunoatf reviewed
Boa! Só precisamos remover e ignoraro conteúdo de node_modules, acho que a sintaxe do git ignore deveria ser node_modules/

2024-10-22 22:01 UTC, Brunoatf requested changes

2024-10-22 22:01 UTC, Brunoatf commented on docker-compose.yml
> +      - NODE_ENV=production
onde essa env é usada?

2024-10-24 15:33 UTC, gmikio commented on docker-compose.yml
> +      - NODE_ENV=production
A variável "NODE_ENV" é uma variável interna utilizada pelo Node.js e React.js a qual define se a build será de Desenvolvimento ou Produção. Caso seja de Produção, diversos pacotes internos são ajustados para tal, otimizando a forma de renderização do React, e também evitando instalar os pacotes designados como "devDependencies", como Logs etc.

2024-10-24 16:10 UTC, gmikio commented on frontend/.eslintrc.json
> +    "no-unused-vars": [
Resolvido o problema de "no_unused_vars" no authStore.js

2024-10-25 02:49 UTC, Brunoatf approved these changes

2024-10-25 04:01 UTC, gmikio commented on docker-compose.yml
> +    environment:
Docker-compose removed. At least for now.

2024-10-25 04:01 UTC, merged